apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "code-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.codeServer.port }}
      targetPort: http
